---
title: "benchmark test"
author: "Daniel Leibovitz"
date: '2021-02-26'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(lattice)
library(flexmix)
library(fdrtool)
library(dplyr)
library(data.table)
library(readr)
library(rnaturalearth)
library(ggnewscale)
library(gtable)
library(ggplot2)
library(RColorBrewer)
library(grid)
library(ggpubr)
library(gganimate)
library(gifski)
library(av)
library(rbenchmark)

# import monotone_mixture code
source("../monotone_mixture/monotone_driver/part_fit.R")
source("../monotone_mixture/monotone_driver/M_driver.R")
source("../monotone_mixture/pseudo_data/data_generator.R")
source("../monotone_mixture/monotone_driver/flex_wrapper.R")

# import GDP/Life expectancy data

lifex <- read.csv("../monotone_mixture/monotone_driver/API_SP.DYN.LE00.IN_DS2_en_csv_v2_1926713.csv", skip = 3)
continent <- read.csv("../monotone_mixture/monotone_driver/Metadata_Country_API_NY.GDP.MKTP.CD_DS2_en_csv_v2_1994746.csv")
gdp2 <- read.csv("../monotone_mixture/monotone_driver/API_NY.GDP.PCAP.CD_DS2_en_csv_v2_1926744.csv", skip=3)
  


lifex$Country.Name <- as.character(lifex$Country.Name)
lifex$Country.Name[which(lifex$Country.Name %in% c(
"Antigua and Barbuda",
"Bahamas, The" ,
"Bosnia and Herzegovina", 
"Brunei Darussalam" ,
"Cabo Verde"  ,
"Cayman Islands", 
"Central African Republic" ,
"Congo, Dem. Rep.", 
"Congo, Rep." ,
"Cote d'Ivoire", 
"Curacao" ,
"Czech Republic", 
"Dominican Republic", 
"Egypt, Arab Rep." ,
"Equatorial Guinea" ,
"Eswatini" ,
"Faroe Islands", 
"French Polynesia", 
"Gambia, The" ,
"Hong Kong SAR, China",
"Iran, Islamic Rep.",
"Korea, Rep." ,
"Kyrgyz Republic", 
"Macao SAR, China", 
"Marshall Islands" ,
"Micronesia, Fed. Sts.", 
"Russian Federation" ,
"Sao Tome and Principe",  
"Sint Maarten (Dutch part)", 
"Slovak Republic" ,
"Solomon Islands" ,
"South Sudan",
"St. Lucia" ,
"St. Vincent and the Grenadines", 
"Syrian Arab Republic",
"Venezuela, RB" ,
"Virgin Islands (U.S.)",
"Yemen, Rep." 
))] <- c( "Antigua and Barb.",
 "Bahamas",
 "Bosnia and Herz." ,
 "Brunei" ,
 "Cape Verde", 
 "Cayman Is." ,
 "Central African Rep.", 
 "Dem. Rep. Congo",
 "Congo",
 "Côte d'Ivoire",
 "Curaçao",
 "Czech Rep.",
 "Dominican Rep.",
"Egypt",
 "Eq. Guinea",
"Swaziland",
"Faeroe Is.",
 "Fr. Polynesia",
"Gambia",
 "Hong Kong",
 "Iran",
 "Korea",
 "Kyrgyzstan",
 "Macao",
 "Marshall Is.",
"Micronesia",
 "Russia",
 "São Tomé and Principe" ,
 "Sint Maarten",
 "Slovakia",
 "Solomon Is.",
 "S. Sudan",
 "Saint Lucia",
 "St. Vin. and Gren.",
 "Syria",
"Venezuela",
 "U.S. Virgin Is.",
 "Yemen"
 )
lifex$Country.Name <- as.factor(lifex$Country.Name)




gdp2$Country.Name <- as.character(gdp2$Country.Name)
gdp2$Country.Name[which(gdp2$Country.Name %in% c(
"Antigua and Barbuda",
"Bahamas, The" ,
"Bosnia and Herzegovina", 
"Brunei Darussalam" ,
"Cabo Verde"  ,
"Cayman Islands", 
"Central African Republic" ,
"Congo, Dem. Rep.", 
"Congo, Rep." ,
"Cote d'Ivoire", 
"Curacao" ,
"Czech Republic", 
"Dominican Republic", 
"Egypt, Arab Rep." ,
"Equatorial Guinea" ,
"Eswatini" ,
"Faroe Islands", 
"French Polynesia", 
"Gambia, The" ,
"Hong Kong SAR, China",
"Iran, Islamic Rep.",
"Korea, Rep." ,
"Kyrgyz Republic", 
"Macao SAR, China", 
"Marshall Islands" ,
"Micronesia, Fed. Sts.", 
"Russian Federation" ,
"Sao Tome and Principe",  
"Sint Maarten (Dutch part)", 
"Slovak Republic" ,
"Solomon Islands" ,
"South Sudan",
"St. Lucia" ,
"St. Vincent and the Grenadines", 
"Syrian Arab Republic",
"Venezuela, RB" ,
"Virgin Islands (U.S.)",
"Yemen, Rep." 
))] <- c( "Antigua and Barb.",
 "Bahamas",
 "Bosnia and Herz." ,
 "Brunei" ,
 "Cape Verde", 
 "Cayman Is." ,
 "Central African Rep.", 
 "Dem. Rep. Congo",
 "Congo",
 "Côte d'Ivoire",
 "Curaçao",
 "Czech Rep.",
 "Dominican Rep.",
"Egypt",
 "Eq. Guinea",
"Swaziland",
"Faeroe Is.",
 "Fr. Polynesia",
"Gambia",
 "Hong Kong",
 "Iran",
 "Korea",
 "Kyrgyzstan",
 "Macao",
 "Marshall Is.",
"Micronesia",
 "Russia",
 "São Tomé and Principe" ,
 "Sint Maarten",
 "Slovakia",
 "Solomon Is.",
 "S. Sudan",
 "Saint Lucia",
 "St. Vin. and Gren.",
 "Syria",
"Venezuela",
 "U.S. Virgin Is.",
 "Yemen"
 )
gdp2$Country.Name <- as.factor(gdp2$Country.Name)
```
```{r clean}

# clean lifex csv
lifex <- lifex[,c(-3, -4, -64, -65, -66)]
names(lifex)[3:61] <- substring(names(lifex)[3:61],2,5)
lifex <- melt(setDT(lifex), id.vars = 1:2, variable.name = "Year")
lifex <- lifex[complete.cases(lifex),]
lifex$Year <- as.integer(as.character(lifex$Year))
names(lifex)[4] <- "LifeExpectancy"
# lifex <- lifex[,-2]

# clean gdp2 csv
gdp2 <- gdp2[,c(-2,-3, -4, -64, -65, -66)]
names(gdp2)[2:60] <- substring(names(gdp2)[2:60],2,5)
gdp2 <- melt(setDT(gdp2), id.vars = 1, variable.name = "Year")
gdp2 <- gdp2[complete.cases(gdp2),]
gdp2$Year <- as.integer(as.character(gdp2$Year))
names(gdp2)[3] <- "GDP"


# merge
le <- merge(lifex, gdp2, by.x = c("Country.Name", "Year"), by.y = c("Country.Name", "Year"))

continent <- merge(le, continent, by.x = c("Country.Code"), by.y = c("Country.Code"))

le <- le[,-3] # remove country code

```

```{r pseudo, eval=T}
# data with 4 latent categories

################
X <- cbind(
  runif(1000, -5, 5),
  runif(1000, -10, 10),
  runif(1000, -100, 100),
  runif(1000, -100, 100),
  runif(1000, -100, 100)
)
################

# print benchmarks (all excluding intercept)
benchmark(
"Univariate non-parametric" = {
  Y1 <- (X[1:250,1])+3 + rnorm(250, 0, 3) # component 1
  Y2 <- (X[251:500,1])^3 + rnorm(250, 0, 4) # component 2
  Y3 <- 2*((X[501:750,1])+5) + rnorm(250, 0, 3) # component 3
  Y4 <- 2*((X[751:1000,1])-5) + rnorm(250, 0, 4) # component 4
  df_3 <- data.frame(c(Y1, Y2, Y3, Y4), X)
  names(df_3) <- c("Y", "X1", "X2", "X3", "X4", "X5")
  ###
  m1 <- flexmix(Y ~ X1 -1, data = df_3, k = 4, 
                model = mono_reg(mon_inc_names = "X1"))
},
"Bivariate non-parametric" = {
  Y1 <- (X[1:250,1])+3 + 1.5*X[1:250,2] + rnorm(250, 0, 3) # component 1
  Y2 <- (X[251:500,1])^3 + 3*X[251:500,2] + rnorm(250, 0, 4) # component 2
  Y3 <- 2*((X[501:750,1])+5) + 5*X[501:750,2] + rnorm(250, 0, 3) # component 3
  Y4 <- 2*((X[751:1000,1])-5) + 10*X[751:1000,2] + rnorm(250, 0, 4) # component 4
  df_3 <- data.frame(c(Y1, Y2, Y3, Y4), X)
  names(df_3) <- c("Y", "X1", "X2", "X3", "X4", "X5")
  ###
  m2 <- flexmix(Y ~ X1 + X2 -1, data = df_3, k = 4, 
                model = mono_reg(mon_inc_names = c("X1", "X2")))
},
"Univariate partially linear" = {
  Y1 <- (X[1:250,1])+3 + 1.5*X[1:250,2] - 1.5*X[1:250,3] - 1*X[1:250,4] + X[1:250,5] + rnorm(250, 0, 3) # component 1
  Y2 <- (X[251:500,1])^3 + 3*X[251:500,2] + 2*X[251:500,3] - 2*X[251:500,4] + 2*X[251:500,5] + rnorm(250, 0, 4) # component 2
  Y3 <- 2*((X[501:750,1])+5) + 5*X[501:750,2] - 1*X[501:750,3] + 2*X[501:750,4] + 4*X[501:750,5] + rnorm(250, 0, 3) # component 3
  Y4 <- 2*((X[751:1000,1])-5) + 10*X[751:1000,2] - 3*X[751:1000,3] - 3*X[751:1000,4] + 3*X[751:1000,5] + rnorm(250, 0, 4) # component 4
  df_3 <- data.frame(c(Y1, Y2, Y3, Y4), X)
  names(df_3) <- c("Y", "X1", "X2", "X3", "X4", "X5")
  ###
  m3 <- flexmix(Y ~ . -1, data = df_3, k = 4, 
                model = mono_reg(mon_inc_names = "X1"))
},
"Bivariate partially linear" = {
  Y1 <- (X[1:250,1])+3 + 1.5*X[1:250,2] - 1.5*X[1:250,3] - 1*X[1:250,4] + X[1:250,5] + rnorm(250, 0, 3) # component 1
  Y2 <- (X[251:500,1])^3 + 3*X[251:500,2] + 2*X[251:500,3] - 2*X[251:500,4] + 2*X[251:500,5] + rnorm(250, 0, 4) # component 2
  Y3 <- 2*((X[501:750,1])+5) + 5*X[501:750,2] - 1*X[501:750,3] + 2*X[501:750,4] + 4*X[501:750,5] + rnorm(250, 0, 3) # component 3
  Y4 <- 2*((X[751:1000,1])-5) + 10*X[751:1000,2] - 3*X[751:1000,3] - 3*X[751:1000,4] + 3*X[751:1000,5] + rnorm(250, 0, 4) # component 4
  df_3 <- data.frame(c(Y1, Y2, Y3, Y4), X)
  names(df_3) <- c("Y", "X1", "X2", "X3", "X4", "X5")
  ###
  m4 <- flexmix(Y ~ . -1, data = df_3, k = 4, model = mono_reg(mon_inc_names = c("X1", "X2")))
},
replications = 2,
columns =
  c("test", "replications", "elapsed", "relative", "sys.self")
)


```